from __future__ import annotations

from route74.storage.connection import DEFAULT_DB, connect, connect_readonly, init_db, load_schema_migrations
from route74.storage.errors import STORAGE_READ_ERRORS
from route74.storage.collector_runs import (
    insert_collector_run,
    prune_collector_runs,
    summarize_collector_runs,
    summarize_collector_runs_for_report_window,
)
from route74.storage.bot_latency import (
    BotInteractionEvent,
    BotLatencyRecorder,
    BotLatencySummary,
    insert_bot_interaction_event,
    summarize_bot_latency,
)
from route74.storage.db_admin import (
    DbBackupResult,
    DbHealthSummary,
    DbLatestTimestamp,
    backup_database,
    summarize_db_health,
    summarize_db_health_readonly,
)
from route74.storage.heartbeat import (
    load_bot_update_offset,
    load_collector_heartbeat,
    save_bot_update_offset,
    update_collector_heartbeat,
)
from route74.storage.models import (
    CollectorHeartbeat,
    CollectorRunSummary,
    CollectorWindowRunSummary,
    CountByKey,
    ForecastCoverageBucket,
    ForecastReadinessSummary,
    ForecastWindowCoverageSummary,
    ReportWindowSummary,
    RouteTrafficSnapshot,
    YandexObservation,
    YandexTelemetrySummary,
)
from route74.storage.forecast_readiness import summarize_yandex_forecast_readiness
from route74.storage.forecast_coverage import summarize_yandex_forecast_window_coverage
from route74.storage.forecast_health import summarize_forecast_health
from route74.storage.forecast_samples import (
    backfill_yandex_forecast_samples,
    count_yandex_forecast_samples,
    insert_yandex_forecast_sample,
)
from route74.storage.history import (
    YandexEtaHistory,
    YandexForecastSampleCounts,
    load_yandex_eta_history_for_profile_window,
    load_yandex_forecast_sample_counts,
)
from route74.storage.prediction_lab import (
    PredictionLabBackfillResult,
    PredictionLabCalibrationBucket,
    PredictionLabCalibrationSummary,
    PredictionLabSourceSummary,
    PredictionLabSummary,
    ResidualCorrection,
    SourceReliability,
    backfill_prediction_lab,
    count_arrival_events,
    count_prediction_evaluations,
    count_prediction_events,
    effective_source_reliability,
    evaluate_pending_predictions,
    load_arrival_events,
    load_residual_correction,
    load_source_reliability,
    summarize_prediction_lab_calibration,
    summarize_prediction_lab_window,
    touch_route_geometry,
    upsert_route_geometry,
)
from route74.storage.route_geometry import route_geometry_cache_status
from route74.storage.report_windows import (
    backfill_report_window_snapshots,
    count_report_window_snapshots,
    insert_report_window_snapshot,
    summarize_report_windows,
)
from route74.storage.yandex_snapshots import (
    count_yandex_observations,
    count_yandex_snapshots,
    insert_yandex_snapshot,
    latest_yandex_snapshot_sampled_at,
    load_yandex_observations,
    prune_yandex_telemetry,
    summarize_yandex_telemetry,
)
from route74.storage.yandex_canary import (
    YandexCanaryHealth,
    YandexCanaryRun,
    insert_yandex_canary_run,
    summarize_yandex_canary_health,
)
from route74.storage.runtime_quality import (
    BotRuntimeCalibration,
    BotRuntimeCalibrationGroup,
    BotRuntimePrediction,
    BotRuntimePredictionQuality,
    BotRuntimePredictionQualityGroup,
    load_recent_bot_runtime_predictions,
    summarize_bot_runtime_calibration,
    summarize_bot_runtime_predictions,
)

__all__ = [
    "DEFAULT_DB",
    "STORAGE_READ_ERRORS",
    "CollectorHeartbeat",
    "BotInteractionEvent",
    "BotRuntimeCalibration",
    "BotRuntimeCalibrationGroup",
    "BotLatencyRecorder",
    "BotLatencySummary",
    "BotRuntimePrediction",
    "BotRuntimePredictionQuality",
    "BotRuntimePredictionQualityGroup",
    "CollectorRunSummary",
    "CollectorWindowRunSummary",
    "CountByKey",
    "DbBackupResult",
    "DbHealthSummary",
    "DbLatestTimestamp",
    "ForecastCoverageBucket",
    "ForecastReadinessSummary",
    "ForecastWindowCoverageSummary",
    "PredictionLabCalibrationBucket",
    "PredictionLabCalibrationSummary",
    "PredictionLabSourceSummary",
    "PredictionLabSummary",
    "PredictionLabBackfillResult",
    "ReportWindowSummary",
    "ResidualCorrection",
    "SourceReliability",
    "RouteTrafficSnapshot",
    "YandexObservation",
    "YandexEtaHistory",
    "YandexForecastSampleCounts",
    "YandexCanaryHealth",
    "YandexCanaryRun",
    "YandexTelemetrySummary",
    "backfill_report_window_snapshots",
    "backfill_prediction_lab",
    "backfill_yandex_forecast_samples",
    "connect",
    "connect_readonly",
    "count_arrival_events",
    "count_prediction_evaluations",
    "count_prediction_events",
    "count_report_window_snapshots",
    "count_yandex_forecast_samples",
    "count_yandex_observations",
    "count_yandex_snapshots",
    "effective_source_reliability",
    "evaluate_pending_predictions",
    "init_db",
    "load_schema_migrations",
    "insert_collector_run",
    "insert_bot_interaction_event",
    "insert_report_window_snapshot",
    "insert_yandex_forecast_sample",
    "insert_yandex_snapshot",
    "insert_yandex_canary_run",
    "latest_yandex_snapshot_sampled_at",
    "load_bot_update_offset",
    "load_collector_heartbeat",
    "load_arrival_events",
    "load_residual_correction",
    "load_recent_bot_runtime_predictions",
    "load_source_reliability",
    "load_yandex_eta_history_for_profile_window",
    "load_yandex_forecast_sample_counts",
    "load_yandex_observations",
    "prune_yandex_telemetry",
    "prune_collector_runs",
    "route_geometry_cache_status",
    "save_bot_update_offset",
    "summarize_yandex_forecast_readiness",
    "summarize_yandex_forecast_window_coverage",
    "summarize_collector_runs",
    "summarize_bot_latency",
    "summarize_bot_runtime_calibration",
    "summarize_bot_runtime_predictions",
    "summarize_collector_runs_for_report_window",
    "backup_database",
    "summarize_db_health",
    "summarize_db_health_readonly",
    "summarize_forecast_health",
    "summarize_prediction_lab_calibration",
    "summarize_prediction_lab_window",
    "summarize_report_windows",
    "summarize_yandex_telemetry",
    "summarize_yandex_canary_health",
    "touch_route_geometry",
    "update_collector_heartbeat",
    "upsert_route_geometry",
]
